const stages=[
{icon:'🧠',short:'Learn',title:'Teach the AI',summary:'Train a small GPT to predict what comes next.',changed:'Raw text becomes next-token training examples.',why:'This creates the model that later stages accelerate and scale.',output:'A trained checkpoint that can generate text.',tech:'Character tokenizer + dataset + decoder-only Transformer + cross-entropy + AdamW.',viz:'learn'},
{icon:'⚡',short:'Scale',title:'Add More GPU Workers',summary:'Several GPUs learn from different batches at the same time.',changed:'One model becomes synchronized replicas across workers.',why:'More workers can increase throughput when communication is controlled.',output:'A measurable multi-GPU throughput curve.',tech:'PyTorch DDP + DistributedSampler + NCCL AllReduce; CPU/Gloo correctness is testable.',viz:'ddp'},
{icon:'📦',short:'Fit',title:'Fit a Bigger Model',summary:'Divide training state across workers instead of duplicating it.',changed:'Parameters, gradients and optimizer state can be sharded.',why:'Lower per-GPU memory enables larger jobs.',output:'A DDP-vs-FSDP memory and throughput comparison.',tech:'FSDP FULL_SHARD + activation checkpointing.',viz:'fsdp'},
{icon:'🚀',short:'Optimize',title:'Make GPU Operations Faster',summary:'Optimize selected operations below the PyTorch level.',changed:'Custom CUDA implementations cover vector addition and RMSNorm.',why:'Repeated kernel costs can affect end-to-end training.',output:'Kernel latency and correctness comparisons.',tech:'CUDA C++ extension + RMSNorm + vector add + PyTorch fallback.',viz:'cuda'},
{icon:'📊',short:'Prove',title:'Measure the Improvement',summary:'Optimization only matters when measurements prove it.',changed:'Precision, DataLoader, CUDA and scaling experiments become benchmarks.',why:'Measurements separate real gains from assumptions.',output:'Tokens/sec, step time, memory, latency and scaling evidence.',tech:'Benchmark scripts + RESULTS.md; unavailable GPU results stay N/A.',viz:'bench'},
{icon:'🖥️',short:'Cluster',title:'Scale Beyond One Computer',summary:'SLURM can schedule training across GPU machines.',changed:'The job becomes multi-node and schedulable.',why:'Large workloads need more compute than one server.',output:'SLURM execution plus monitoring.',tech:'SLURM + torchrun + NCCL + metrics logger + GPU monitor.',viz:'hpc'},
{icon:'💬',short:'Serve',title:'Let People Use the Model',summary:'Turn the checkpoint into a prompt-to-response service.',changed:'The model is wrapped in FastAPI and packaged for deployment.',why:'Training becomes a usable product.',output:'FastAPI endpoints plus this interactive chat.',tech:'FastAPI /health, /generate and /generate_batch + Docker.',viz:'serve'}];
const tabs=document.querySelector('#stageTabs');
stages.forEach(function(s,i){const b=document.createElement('button');b.className='stage-tab';b.textContent=s.icon+' '+(i+1)+'. '+s.short;b.onclick=function(){renderStage(i)};tabs.appendChild(b)});
function gpu(n,fsdp){return '<div class="gpu"><b>GPU '+n+'</b><small>'+(fsdp?'shard':'worker')+'</small>'+(fsdp?'<div class="shard"></div>':'')+'</div>'}
function diagram(type){if(type==='learn')return '<div class="diagram"><div class="node">Machine learning is …</div><div class="arrow">↓</div><div class="node">🧠 Mini GPT<br><small>learns next-token patterns</small></div><div class="arrow">↓</div><div class="node">Generated continuation</div></div>';if(type==='ddp')return '<div class="diagram"><div class="node">📚 Training data</div><div class="arrow">↓ split work ↓</div><div class="row">'+[1,2,3,4].map(function(x){return gpu(x,false)}).join('')+'</div><div class="arrow">↕ synchronize ↕</div><div class="node">Synchronized model</div></div>';if(type==='fsdp')return '<div class="diagram"><div class="node">Large training state</div><div class="arrow">↓ shard ↓</div><div class="row">'+[1,2,3,4].map(function(x){return gpu(x,true)}).join('')+'</div><div class="arrow">↓</div><div class="node">Less duplicated memory</div></div>';if(type==='cuda')return '<div class="diagram"><div class="node">GPU memory</div><div class="arrow">↓ parallel work ↓</div><div class="row"><div class="gpu">⚡<small>threads</small></div><div class="gpu">⚡<small>threads</small></div><div class="gpu">⚡<small>threads</small></div><div class="gpu">⚡<small>threads</small></div></div><div class="arrow">↓</div><div class="node">Faster selected operation</div></div>';if(type==='bench')return '<div class="diagram"><div class="node">Baseline</div><div class="arrow">↓ measure</div><div class="node">Change one thing</div><div class="arrow">↓ measure again</div><div class="node">📊 Evidence</div></div>';if(type==='hpc')return '<div class="diagram"><div class="node">SLURM job manager</div><div class="arrow">↓ allocate machines</div><div class="row"><div class="gpu">Node 1<small>GPU × N</small></div><div class="gpu">Node 2<small>GPU × N</small></div><div class="gpu">Node 3<small>GPU × N</small></div></div><div class="arrow">↔ network ↔</div></div>';return '<div class="diagram"><div class="node">You type a prompt</div><div class="arrow">↓</div><div class="node">FastAPI → GPT → GPU</div><div class="arrow">↓</div><div class="node">💬 Generated response</div></div>'}
function renderStage(i){const s=stages[i];Array.from(tabs.children).forEach(function(x,j){x.classList.toggle('active',i===j)});stageKicker.textContent='PHASE '+(i+1)+' · '+s.icon+' '+s.short.toUpperCase();stageTitle.textContent=s.title;stageSummary.textContent=s.summary;stageChanged.textContent=s.changed;stageWhy.textContent=s.why;stageOutput.textContent=s.output;stageTech.textContent=s.tech;stageViz.innerHTML=diagram(s.viz)}renderStage(0);
const techToggle=document.querySelector('#techToggle');techToggle.onclick=function(){document.body.classList.toggle('tech-on');techToggle.textContent='Technical details: '+(document.body.classList.contains('tech-on')?'On':'Off')};
const slider=document.querySelector('#gpuSlider'),workers=document.querySelector('#gpuWorkers'),count=document.querySelector('#gpuCount'),sim=document.querySelector('#simExplain');function renderWorkers(){const n=Number(slider.value);count.textContent=n+' GPU'+(n>1?'s':'');workers.innerHTML=Array.from({length:n},function(_,i){return '<div class="worker"><div><span>▣</span><br><small>GPU '+(i+1)+'</small></div></div>'}).join('');sim.textContent=n===1?'One worker handles the training batches.':n+' workers can process batches in parallel, but they must communicate to stay synchronized.'}slider.oninput=renderWorkers;renderWorkers();
const info={gpu:['Unlock the CUDA result','Run the CUDA benchmark on an NVIDIA machine with nvcc. Record PyTorch, naive CUDA and optimized CUDA latency.'],scale:['Benchmark real multi-GPU scaling','Run DDP with 1, 2, 4 and 8 NVIDIA GPUs using NCCL and record tokens/sec and scaling efficiency.'],fsdp:['Measure DDP vs FSDP','Record peak GPU memory, tokens/sec and step time on the same hardware.'],hpc:['Produce the HPC result','Submit the provided SLURM jobs on a GPU cluster and compare throughput and communication overhead.']};
const modal=document.querySelector('#infoModal');document.querySelectorAll('[data-modal]').forEach(function(b){b.onclick=function(){const x=info[b.dataset.modal];modalTitle.textContent=x[0];modalBody.innerHTML='<p>'+x[1]+'</p>';modal.showModal()}});document.querySelectorAll('dialog .close').forEach(function(b){b.onclick=function(){b.closest('dialog').close()}});
let apiBase=localStorage.getItem('dg_api')||'http://localhost:8000';const status=document.querySelector('#apiStatus'),statusText=document.querySelector('#apiStatusText');async function checkApi(){try{const r=await fetch(apiBase+'/health',{signal:AbortSignal.timeout(1800)}),d=await r.json();if(r.ok&&d.status==='ok'){status.style.background='var(--good)';statusText.textContent='Model ready on '+(d.device||'device');return true}status.style.background='var(--warn)';statusText.textContent='API reachable, but no trained checkpoint is loaded';return false}catch(e){status.style.background='#71839a';statusText.textContent='Demo mode · inference API not connected';return false}}checkApi();
const settingsBtn=document.querySelector('#settingsBtn'),settingsModal=document.querySelector('#settingsModal'),saveApi=document.querySelector('#saveApi'),apiBaseInput=document.querySelector('#apiBase');settingsBtn.onclick=function(){apiBaseInput.value=apiBase;settingsModal.showModal()};saveApi.onclick=function(){apiBase=apiBaseInput.value.replace(/\/$/,'');localStorage.setItem('dg_api',apiBase);settingsModal.close();checkApi()};
const form=document.querySelector('#chatForm'),messages=document.querySelector('#messages'),meta=document.querySelector('#generationMeta');function addMsg(kind,text){const d=document.createElement('div');d.className='message '+kind;d.innerHTML='<span>'+(kind==='user'?'YOU':'DG')+'</span><p></p>';d.querySelector('p').textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;return d.querySelector('p')}
form.onsubmit=async function(e){e.preventDefault();const input=document.querySelector('#prompt'),prompt=input.value.trim();if(!prompt)return;addMsg('user',prompt);input.value='';const out=addMsg('assistant','Thinking…');meta.textContent='';try{const r=await fetch(apiBase+'/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:prompt,max_new_tokens:80,temperature:.8,top_k:50})});if(!r.ok)throw new Error((await r.json()).detail||'HTTP '+r.status);const d=await r.json();out.textContent=d.generated_text;meta.textContent='Generated by your model · '+Math.round(d.latency_ms)+' ms · '+d.device;checkApi()}catch(err){out.textContent='Demo mode: your browser would send “'+prompt+'” to the FastAPI /generate endpoint. Connect a trained checkpoint to see the real output.';meta.textContent='Backend not available ('+err.message+'). No fake model response was generated.'}};